"""Tests for the keyring: the age key's round trip into Infisical and back.

Two failure modes are worth a suite here, and neither is a crash.

The first is storing something that is not the key. A truncated paste, an SSH
private key, the public half by mistake -- all of them upload cleanly, all of
them look right in the UI, and all of them are discovered at the next
activation of whichever host pulled them. So the checksum path is tested
against real ``age-keygen`` output rather than against a round trip through
this module's own encoder, which would only prove it agrees with itself.

The second is a successful run that quietly widens who can read the key: an
overwrite that strands every host already holding the old one, a group grant
that hands the estate's master key to a team, an install path that points
somewhere the host was using for something else.

Everything is offline. The key vectors below were generated by ``age-keygen``
for this file and have never encrypted anything.
"""

from __future__ import annotations

import grp
import os
import pwd
from pathlib import Path
from typing import Any

import pytest

from nixfisical.api import InfisicalError
from nixfisical.keyring import (
    AGE,
    ENVIRONMENT,
    KEY_GROUP,
    KEY_MODE,
    KEY_OWNER,
    KEY_PATH,
    KEY_PUBLIC,
    KEY_PUBLIC_PATH,
    KEY_SECRET,
    KEY_TYPE,
    SSH,
    KeyringError,
    Placement,
    audit,
    install,
    parse_age_key_file,
    push,
)

# The SSH vectors live next door, where the parser that reads them is tested.
# Copying them here would give two files that can drift into disagreeing about
# what a valid key looks like.
from test_material import SSH_ED25519, SSH_ED25519_PUB
from test_material import SSH_ED25519_COMMENT as SSH_COMMENT

SECRET_A = "AGE-SECRET-KEY-1NXC4U76NRFG5S3C44J9K3ZATCRET0039Y753NN30UU58ZTY89C6S40CR7W"
PUBLIC_A = "age1sy4gt0mt0dasaygrfhhkarx7q2wpe5uysd09stqv7qh5hnpzlcnq9z9wz5"
SECRET_B = "AGE-SECRET-KEY-1G955PJ5P6E3HJRFY7C3Q7HHUACVK5Z059MRHN5MUVAW6W2V7QRXSGK3YCS"
PUBLIC_B = "age1lu068w3m2dmd6jm9yzkx0725uhd73wpk495z2r6srxs2d8j2caxqvh36qq"

KEY_FILE_A = f"# created: 2026-09-14T02:10:51Z\n# public key: {PUBLIC_A}\n{SECRET_A}\n"


class FakeClient:
    """Enough of InfisicalClient to answer the questions this module asks."""

    def __init__(
        self,
        *,
        projects: dict[str, str] | None = None,
        secrets: list[dict[str, Any]] | None = None,
        users: dict[str, str] | None = None,
        groups: dict[str, str] | None = None,
        identities: dict[str, str] | None = None,
    ) -> None:
        self.projects = dict(projects or {})
        self.secrets = list(secrets or [])
        self.users = dict(users or {})
        self.groups = dict(groups or {})
        self.identities = dict(identities or {})
        self.created_projects: list[str] = []
        self.written: dict[str, str] = {}
        self.added_users: list[tuple[str, str]] = []

    # -- reads
    def list_projects(self, organization_id: str) -> dict[str, str]:
        return dict(self.projects)

    def list_secrets(self, *, project_id: str, environment: str, path: str = "/"):
        return list(self.secrets)

    def list_project_users(self, project_id: str) -> dict[str, str]:
        return dict(self.users)

    def list_project_groups(self, project_id: str) -> dict[str, str]:
        return dict(self.groups)

    def list_project_identities(self, project_id: str) -> dict[str, str]:
        return dict(self.identities)

    # -- writes
    def create_project(self, name: str) -> str:
        self.created_projects.append(name)
        self.projects[name] = "new-project"
        return "new-project"

    def create_environment(self, project_id: str, *, name: str, slug: str) -> bool:
        return True

    def create_folder(self, *, project_id, environment, path, name) -> bool:
        return True

    def upsert_secret(self, name, *, project_id, environment, secret_path, value) -> str:
        existed = name in self.written
        self.written[name] = value
        return "updated" if existed else "created"

    def add_user_to_project(self, *, project_id: str, email: str, role: str) -> None:
        self.added_users.append((email, role))
        self.users[email.lower()] = role


def stored(folder: str, key: str, value: str) -> dict[str, Any]:
    return {"secretPath": folder, "secretKey": key, "secretValue": value}


# The agent's `materialise` chowns before it renames, and only root may chown
# to root. Placement is orthogonal to that, so the install tests below store an
# ownership this process can actually apply -- its own -- and the real
# root:root default is covered by `test_default_placement_is_accepted`.
_USER = pwd.getpwuid(os.getuid()).pw_name


def _own_group() -> str:
    for gid in (os.getgid(), pwd.getpwuid(os.getuid()).pw_gid):
        try:
            return grp.getgrgid(gid).gr_name
        except KeyError:
            continue
    return _USER


_GROUP = _own_group()


def placement_at(destination: Path) -> list[dict[str, Any]]:
    return [
        stored("/fleet", KEY_PATH, str(destination)),
        stored("/fleet", KEY_OWNER, _USER),
        stored("/fleet", KEY_GROUP, _GROUP),
    ]


# -- what counts as an age key ----------------------------------------------


def test_parses_a_real_age_key_file() -> None:
    assert parse_age_key_file(KEY_FILE_A) == [SECRET_A]


def test_keeps_every_key_in_a_multi_key_file() -> None:
    """A rekeying is two keys in one file; dropping the second is a lockout."""
    assert parse_age_key_file(f"{SECRET_A}\n{SECRET_B}\n") == [SECRET_A, SECRET_B]


def test_rejects_a_truncated_key() -> None:
    """The whole reason the checksum is verified rather than the prefix."""
    with pytest.raises(KeyringError, match="checksum"):
        parse_age_key_file(SECRET_A[:-1] + "A")


def test_rejects_the_public_half() -> None:
    with pytest.raises(KeyringError, match="not a comment nor|neither a comment"):
        parse_age_key_file(f"{PUBLIC_A}\n")


def test_rejects_an_ssh_private_key() -> None:
    with pytest.raises(KeyringError):
        parse_age_key_file(
            "-----BEGIN OPENSSH PRIVATE KEY-----\nb3BlbnNzaC1rZXk=\n"
            "-----END OPENSSH PRIVATE KEY-----\n"
        )


def test_rejects_a_comments_only_file() -> None:
    with pytest.raises(KeyringError, match="no age secret key"):
        parse_age_key_file(f"# public key: {PUBLIC_A}\n")


# -- placement ---------------------------------------------------------------


def test_relative_install_path_is_refused() -> None:
    with pytest.raises(KeyringError, match="relative"):
        Placement(path="var/lib/sops-nix/key.txt").validated_path()


def test_traversing_install_path_is_refused() -> None:
    with pytest.raises(KeyringError, match="traverses"):
        Placement(path="/var/lib/../../etc/shadow").validated_path()


def test_group_readable_mode_is_refused() -> None:
    with pytest.raises(KeyringError, match="readable beyond its owner"):
        Placement(mode="0440").validated_mode()


def test_default_placement_is_accepted() -> None:
    placement = Placement()
    assert placement.validated_path() == Path("/var/lib/sops-nix/key.txt")
    assert placement.validated_mode() == 0o400


# -- push --------------------------------------------------------------------


def test_push_creates_the_project_and_stores_the_key() -> None:
    client = FakeClient()
    summary = push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email="admin@example.com",
    )
    assert summary.ok, summary.errors
    assert client.created_projects == ["keyring"]
    # Verbatim, comments included: the '# public key:' lines are what an
    # operator without age-keygen reads the recipient from.
    assert client.written[KEY_SECRET] == KEY_FILE_A
    assert client.written[KEY_PATH] == "/var/lib/sops-nix/key.txt"
    assert client.written[KEY_OWNER] == "root"
    assert client.written[KEY_MODE] == "0400"
    assert PUBLIC_A in client.written[KEY_PUBLIC]


def test_push_adds_the_superadmin_because_a_new_project_is_visible_to_nobody() -> None:
    client = FakeClient()
    push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email="admin@example.com",
    )
    assert client.added_users == [("admin@example.com", "admin")]


def test_push_does_not_re_add_an_operator_already_on_the_project() -> None:
    client = FakeClient(
        projects={"keyring": "k1"}, users={"admin@example.com": "admin"}
    )
    push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email="admin@example.com",
    )
    assert client.added_users == []


def test_push_refuses_to_overwrite_an_existing_key() -> None:
    """The destructive case: every host holding the old key is stranded."""
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PUBLIC, PUBLIC_A),
        ],
    )
    summary = push(
        client,
        name="fleet",
        key_text=f"{SECRET_B}\n",
        organization_id="org",
        operator_email=None,
    )
    assert not summary.ok
    assert "Refusing to overwrite" in " ".join(summary.errors)
    assert PUBLIC_A in " ".join(summary.errors)  # names what is already there
    assert client.written == {}


def test_push_replaces_when_told_to() -> None:
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[stored("/fleet", KEY_SECRET, KEY_FILE_A)],
    )
    summary = push(
        client,
        name="fleet",
        key_text=f"{SECRET_B}\n",
        organization_id="org",
        operator_email=None,
        replace=True,
    )
    assert summary.ok, summary.errors
    assert summary.replaced
    assert client.written[KEY_SECRET] == f"{SECRET_B}\n"


def test_push_validates_before_it_creates_anything() -> None:
    """A bad key must not leave a project behind that looks provisioned."""
    client = FakeClient()
    summary = push(
        client,
        name="fleet",
        key_text=SECRET_A[:-1] + "A",
        organization_id="org",
        operator_email="admin@example.com",
    )
    assert not summary.ok
    assert client.created_projects == []
    assert client.written == {}


def test_push_rejects_a_placement_the_host_would_refuse() -> None:
    client = FakeClient()
    summary = push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email=None,
        placement=Placement(path="keys/age.key"),
    )
    assert not summary.ok
    assert client.created_projects == []


def test_push_dry_run_writes_nothing() -> None:
    client = FakeClient()
    summary = push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email="admin@example.com",
        dry_run=True,
    )
    assert summary.ok
    assert client.created_projects == []
    assert client.written == {}
    assert client.added_users == []


# -- audit -------------------------------------------------------------------


def test_audit_is_quiet_when_only_the_superadmin_can_read() -> None:
    client = FakeClient(
        projects={"keyring": "k1"},
        users={"admin@example.com": "admin"},
        secrets=[stored("/fleet", KEY_SECRET, KEY_FILE_A)],
    )
    report = audit(client, organization_id="org", operator_email="admin@example.com")
    assert report.ok
    assert report.warnings == []
    assert report.keys == ["fleet"]


def test_audit_warns_about_a_group() -> None:
    """The failure this exists for: the keyring named in the manifest."""
    client = FakeClient(
        projects={"keyring": "k1"},
        users={"admin@example.com": "admin"},
        groups={"developers": "viewer"},
    )
    report = audit(client, organization_id="org", operator_email="admin@example.com")
    assert any("developers" in warning for warning in report.warnings)
    assert any("manifest" in warning for warning in report.warnings)


def test_audit_warns_about_a_second_human() -> None:
    client = FakeClient(
        projects={"keyring": "k1"},
        users={"admin@example.com": "admin", "intern@example.com": "viewer"},
    )
    report = audit(client, organization_id="org", operator_email="admin@example.com")
    assert any("intern@example.com" in warning for warning in report.warnings)


def test_audit_warns_when_the_superadmin_cannot_open_it() -> None:
    client = FakeClient(projects={"keyring": "k1"}, users={})
    report = audit(client, organization_id="org", operator_email="admin@example.com")
    assert any("NOT on the keyring" in warning for warning in report.warnings)


def test_audit_does_not_flag_host_identities() -> None:
    """A host with viewer is the feature working, not a finding."""
    client = FakeClient(
        projects={"keyring": "k1"},
        users={"admin@example.com": "admin"},
        identities={"id-cli-proxy": "viewer"},
    )
    report = audit(client, organization_id="org", operator_email="admin@example.com")
    assert report.warnings == []
    assert report.identities == {"id-cli-proxy": "viewer"}


# -- install -----------------------------------------------------------------


def test_install_places_the_key_where_the_instance_says(tmp_path: Path) -> None:
    destination = tmp_path / "sops-nix" / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PUBLIC, PUBLIC_A),
            *placement_at(destination),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert summary.ok, summary.errors
    assert summary.written
    assert destination.read_text() == KEY_FILE_A
    assert oct(destination.stat().st_mode & 0o777) == "0o400"
    assert summary.public == [PUBLIC_A]


def test_install_is_a_no_op_when_the_key_has_not_changed(tmp_path: Path) -> None:
    destination = tmp_path / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            *placement_at(destination),
        ],
    )
    assert install(client, name="fleet", organization_id="org").written
    second = install(client, name="fleet", organization_id="org")
    assert second.ok and second.unchanged and not second.written


def test_install_refuses_a_key_the_instance_mangled(tmp_path: Path) -> None:
    """Fetched material is validated before it replaces a working key."""
    destination = tmp_path / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, SECRET_A[:-1] + "A"),
            stored("/fleet", KEY_PATH, str(destination)),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert not destination.exists()


def test_install_will_not_clobber_a_file_that_is_not_an_age_key(tmp_path: Path) -> None:
    """The mitigation for an install path nobody on this host chose."""
    destination = tmp_path / "shadow"
    destination.write_text("root:!:19000:0:99999:7:::\n")
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PATH, str(destination)),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert "Refusing to overwrite" in " ".join(summary.errors)
    assert destination.read_text().startswith("root:")


def test_install_refuses_a_relative_path_from_the_instance() -> None:
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PATH, "relative/key.txt"),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert "relative" in " ".join(summary.errors)


def test_install_path_override_wins_and_says_so(tmp_path: Path) -> None:
    elsewhere = tmp_path / "elsewhere.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PATH, "/var/lib/sops-nix/key.txt"),
            stored("/fleet", KEY_OWNER, _USER),
            stored("/fleet", KEY_GROUP, _GROUP),
        ],
    )
    summary = install(
        client, name="fleet", organization_id="org", path_override=str(elsewhere)
    )
    assert summary.ok, summary.errors
    assert elsewhere.read_text() == KEY_FILE_A
    assert any("overridden" in action for action in summary.actions)


def test_install_names_the_grant_when_the_project_is_invisible() -> None:
    """The error a host hits before anyone runs provision-host for it."""
    client = FakeClient(projects={})
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert "provision-host" in " ".join(summary.errors)


def test_install_reports_a_missing_entry_rather_than_writing_nothing_quietly() -> None:
    client = FakeClient(projects={"keyring": "k1"}, secrets=[])
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert KEY_SECRET in " ".join(summary.errors)


def test_install_dry_run_writes_nothing(tmp_path: Path) -> None:
    destination = tmp_path / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_PATH, str(destination)),
        ],
    )
    summary = install(client, name="fleet", organization_id="org", dry_run=True)
    assert summary.ok
    assert not destination.exists()


def test_install_surfaces_an_api_failure(tmp_path: Path) -> None:
    class Broken(FakeClient):
        def list_secrets(self, **_: Any):
            raise InfisicalError("503 from the instance")

    summary = install(
        Broken(projects={"keyring": "k1"}), name="fleet", organization_id="org"
    )
    assert not summary.ok
    assert "503" in " ".join(summary.errors)


def test_install_ignores_other_entries_in_the_same_project(tmp_path: Path) -> None:
    """One project holds several keyrings; the folder is what selects one."""
    destination = tmp_path / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/other", KEY_SECRET, f"{SECRET_B}\n"),
            stored("/other", KEY_PATH, "/should/not/be/used"),
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            *placement_at(destination),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert summary.ok, summary.errors
    assert destination.read_text() == KEY_FILE_A


def test_environment_is_the_only_one() -> None:
    """Key material has no dev/staging; a second environment is a mistake."""
    assert ENVIRONMENT == "prod"


# -- ssh entries -------------------------------------------------------------
#
# The type layer is tested on its own in test_material.py. What is tested here
# is the part that layer cannot see: that an entry carries its type across the
# instance, that the placement it lands with is the type's and not age's, and
# that the public half is written beside the private one.


def ssh_placement_at(destination: Path) -> list[dict[str, Any]]:
    return [
        stored("/laptop", KEY_TYPE, "ssh"),
        stored("/laptop", KEY_PATH, str(destination)),
        stored("/laptop", KEY_PUBLIC_PATH, f"{destination}.pub"),
        stored("/laptop", KEY_MODE, "0600"),
        stored("/laptop", KEY_OWNER, _USER),
        stored("/laptop", KEY_GROUP, _GROUP),
    ]


def test_push_sniffs_an_ssh_key_and_stores_its_type() -> None:
    client = FakeClient()
    summary = push(
        client,
        name="laptop",
        key_text=SSH_ED25519,
        organization_id="org",
        operator_email=None,
    )
    assert summary.ok, summary.errors
    assert summary.key_type == "ssh"
    assert client.written[KEY_TYPE] == "ssh"
    assert client.written[KEY_SECRET] == SSH_ED25519
    assert client.written[KEY_PUBLIC] == SSH_ED25519_PUB


def test_an_ssh_entry_does_not_inherit_the_age_placement() -> None:
    """The bug this exists to prevent: an SSH key stored at the sops-nix path.

    Nothing would fail at push time, nothing would fail at install time, and
    sops-nix on that host would then find an SSH key where its age key belongs.
    """
    client = FakeClient()
    push(
        client,
        name="laptop",
        key_text=SSH_ED25519,
        organization_id="org",
        operator_email=None,
    )
    assert client.written[KEY_PATH] == SSH.default_path
    assert client.written[KEY_MODE] == "0600"
    assert client.written[KEY_PUBLIC_PATH] == SSH.default_path + ".pub"


def test_an_age_entry_stores_no_public_path() -> None:
    """No file is written for it, so a path for one would be a value with no
    meaning that a later reader would try to honour."""
    client = FakeClient()
    push(
        client,
        name="fleet",
        key_text=KEY_FILE_A,
        organization_id="org",
        operator_email=None,
    )
    assert KEY_PUBLIC_PATH not in client.written


def test_push_prefers_the_sidecar_pub_because_it_carries_the_comment() -> None:
    client = FakeClient()
    summary = push(
        client,
        name="laptop",
        key_text=SSH_ED25519,
        organization_id="org",
        operator_email=None,
        public_override=f"{SSH_ED25519_PUB} {SSH_COMMENT}\n",
    )
    assert summary.ok, summary.errors
    assert client.written[KEY_PUBLIC] == f"{SSH_ED25519_PUB} {SSH_COMMENT}"


def test_push_refuses_an_ssh_key_declared_as_age() -> None:
    """`--type` forcing the wrong answer must fail loudly, not store it."""
    summary = push(
        FakeClient(),
        name="laptop",
        key_text=SSH_ED25519,
        organization_id="org",
        operator_email=None,
        material=AGE,
    )
    assert not summary.ok
    assert "age key file" in " ".join(summary.errors)


def test_install_places_an_ssh_key_and_its_public_half(tmp_path: Path) -> None:
    destination = tmp_path / "id_ed25519"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/laptop", KEY_SECRET, SSH_ED25519),
            stored("/laptop", KEY_PUBLIC, f"{SSH_ED25519_PUB} {SSH_COMMENT}"),
            *ssh_placement_at(destination),
        ],
    )
    summary = install(client, name="laptop", organization_id="org")
    assert summary.ok, summary.errors
    assert summary.key_type == "ssh"
    assert destination.read_text() == SSH_ED25519
    assert oct(destination.stat().st_mode & 0o777) == "0o600"

    public = Path(f"{destination}.pub")
    assert public.read_text() == f"{SSH_ED25519_PUB} {SSH_COMMENT}\n"
    # World-readable on purpose, and from the type table rather than the
    # instance -- see Placement.validated_mode.
    assert oct(public.stat().st_mode & 0o777) == "0o644"
    assert summary.public_written


def test_install_will_not_clobber_a_foreign_file_at_the_public_path(
    tmp_path: Path,
) -> None:
    """The public path is instance-controlled too, and 0644 is not harmless.

    Aiming it at a config file the host reads would be a working attack on a
    host that never touches the private key at all.
    """
    destination = tmp_path / "id_ed25519"
    public = tmp_path / "id_ed25519.pub"
    public.write_text("root:x:0:0:root:/root:/bin/bash\n")
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/laptop", KEY_SECRET, SSH_ED25519),
            stored("/laptop", KEY_PUBLIC, SSH_ED25519_PUB),
            *ssh_placement_at(destination),
        ],
    )
    summary = install(client, name="laptop", organization_id="org")
    assert not summary.ok
    assert KEY_PUBLIC_PATH in " ".join(summary.errors)
    assert public.read_text() == "root:x:0:0:root:/root:/bin/bash\n"
    assert not destination.exists()


def test_install_refuses_an_age_key_where_an_ssh_key_is_declared(
    tmp_path: Path,
) -> None:
    """The instance says ssh and stores something else -- a mixed-up push, or a
    tampered entry. Either way the host must not write it."""
    destination = tmp_path / "id_ed25519"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/laptop", KEY_SECRET, KEY_FILE_A),
            *ssh_placement_at(destination),
        ],
    )
    summary = install(client, name="laptop", organization_id="org")
    assert not summary.ok
    assert not destination.exists()


def test_install_will_not_overwrite_an_ssh_key_with_an_age_key(tmp_path: Path) -> None:
    """The clobber guard is per type, not merely "is this a key of some kind"."""
    destination = tmp_path / "key.txt"
    destination.write_text(SSH_ED25519)
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            *placement_at(destination),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert not summary.ok
    assert destination.read_text() == SSH_ED25519


def test_install_says_so_when_an_ssh_entry_has_no_public_half(tmp_path: Path) -> None:
    """A private key with no `.pub` beside it breaks `ssh -i`, so this is worth
    a line rather than silence -- but it is not worth refusing the private key
    the host came for."""
    destination = tmp_path / "id_ed25519"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/laptop", KEY_SECRET, SSH_ED25519),
            *ssh_placement_at(destination),
        ],
    )
    summary = install(client, name="laptop", organization_id="org")
    assert summary.ok, summary.errors
    assert destination.exists()
    assert not Path(f"{destination}.pub").exists()
    assert "--public-from-file" in " ".join(summary.actions)


def test_an_entry_without_a_type_is_read_as_age(tmp_path: Path) -> None:
    """Entries pushed before KEY_TYPE existed must still install."""
    destination = tmp_path / "key.txt"
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            *placement_at(destination),
        ],
    )
    summary = install(client, name="fleet", organization_id="org")
    assert summary.ok, summary.errors
    assert summary.key_type == "age"


def test_path_override_moves_the_public_half_with_it(tmp_path: Path) -> None:
    """Otherwise --path splits a key pair across two directories, which fails
    later and somewhere else."""
    declared = tmp_path / "declared"
    actual = tmp_path / "actual" / "id_ed25519"
    actual.parent.mkdir()
    client = FakeClient(
        projects={"keyring": "k1"},
        secrets=[
            stored("/laptop", KEY_SECRET, SSH_ED25519),
            stored("/laptop", KEY_PUBLIC, SSH_ED25519_PUB),
            *ssh_placement_at(declared),
        ],
    )
    summary = install(
        client, name="laptop", organization_id="org", path_override=str(actual)
    )
    assert summary.ok, summary.errors
    assert summary.public_path == f"{actual}.pub"
    assert Path(f"{actual}.pub").exists()
    assert not Path(f"{declared}.pub").exists()


def test_audit_names_the_type_of_each_entry() -> None:
    client = FakeClient(
        projects={"keyring": "k1"},
        users={"admin@example.com": "admin"},
        secrets=[
            stored("/fleet", KEY_SECRET, KEY_FILE_A),
            stored("/fleet", KEY_TYPE, "age"),
            stored("/laptop", KEY_SECRET, SSH_ED25519),
            stored("/laptop", KEY_TYPE, "ssh"),
        ],
    )
    report = audit(
        client, organization_id="org", operator_email="admin@example.com"
    )
    assert report.keys == ["fleet", "laptop"]
    assert report.key_types == {"fleet": "age", "laptop": "ssh"}
